### ISSUE TITLE
Jutsu: Earth Wall

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Naruto-Mod#12]
Currently it renders fine but position choosing code needs to be finished as well as the animation tweaked and a few other changes

**Comment by Infinity89** [comment]
Is it already added to the mod?

**Comment by sekwah41** [comment]
It is in pre releases however not fully added

**Comment by sekwah41** [comment]
Need to push entities up when rising then its done

**Comment by caiquemorelli** [comment]
earth wall didnt block kunais and shurikens

**Comment by sekwah41** [comment]
@caiquemorelli thats already known, the issue isnt the wall its actually the kunai and shuriken code which i need to redo.
