### ISSUE TITLE
Mc version

### ISSUE THREAD

**Issue by Infinity89** [sekwah41/Naruto-Mod#14]
Can you update the mod to a new mc version? 1.7.10 is so unstable, it make me crash very often.
I hope you will answer me

**Comment by sekwah41** [comment]
We will be making it in 1.14 using fabric as forge is taking far too long

**Comment by sekwah41** [comment]
Also dw we are abandoning forge altogether, most of the problems solved ;)

**Comment by KLYTB** [comment]
Hello, do you plan to change the mod version to 1.12.2 ? Because the other versions make me bug. Thank you.

**Comment by sekwah41** [comment]
We have no intentions for 1.12.2

**Comment by sekwah41** [comment]
1.16 is now the main focus. I will close this so all issues will be solely to do with problems found with features being made.
