### ISSUE TITLE
Crash while starting the game 

### ISSUE THREAD

**Issue by Foreshawty** [sekwah41/Naruto-Mod#165]
I have both mods and no other.
[crash-2022-07-09_23.31.45-fml.txt](https://github.com/sekwah41/Naruto-Mod/files/9078377/crash-2022-07-09_23.31.45-fml.txt)

**Comment by sekwah41** [comment]
@Foreshawty we will be releasing a fix soon, forge did some large updates in 1.19 so you will need to use an older version until the update comes out https://maven.minecraftforge.net/net/minecraftforge/forge/1.19-41.0.56/forge-1.19-41.0.56-installer.jar

**Comment by sekwah41** [comment]
Basically they removed certain classes and reworked how some stuff works within forge.

Most of the changes are from this large pr https://github.com/MinecraftForge/MinecraftForge/pull/8786
