### ISSUE TITLE
Jutsu: Sexy Jutsu

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Naruto-Mod#17]
Finish making the resources and animations for sexy jutsu

**Comment by Yagah** [comment]
If an opponent is in within 3 or so blocks when used, stuns them for 2 seconds? *However you will need to time it perfectly because upon casting will take 3 seconds to begin working, so that it's not spamable*

*As you see the women from up close you're "Stunned"*

**Comment by sekwah41** [comment]
This will be skipped for now though will be done using the new animation system in the recode
