### ISSUE TITLE
Enchanting render problem

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Naruto-Mod#2]
Enchanted items(gunbai at least) seem to cause the chakra gui to become transparent. I have never noticed it in the forge survival but I will have to check it out to find what cases it in at least some cases.

-- Found by liam

**Comment by Gutorap** [comment]
Agreed

2016-02-11 21:22 GMT-03:00 sekwah41 <notifications@github.com>:

**Comment by sekwah41** [comment]
fixed
