### ISSUE TITLE
how to use jutsu it shows not bound v not bound in justu list

### ISSUE THREAD

**Issue by anujsharer** [sekwah41/Naruto-Mod#218]

**Comment by sekwah41** [comment]
If it's not bound you have unbound it. It's bound by default.

**Comment by sekwah41** [comment]
Just go into the game setting and re-bind it if you need to.

**Comment by anujsharer** [comment]
Thanks for help . Your mod is very good . As a naruto fan I will say you
should add more jutsu like rasenshruken , some earth style . It will make
it even better
