### ISSUE TITLE
narutomod-0.5.0b8.jar crash

### ISSUE THREAD

**Issue by miritoo** [sekwah41/Naruto-Mod#22]
from the b8 version of the naruto mod I have the problem that when I scroll down in the creative inventory my game crashes
![mc naruto mod error](https://user-images.githubusercontent.com/50178255/57028922-a3017800-6c40-11e9-94b6-c42389e2029c.PNG)

**Comment by sekwah41** [comment]
Could I have any more of the log? It would tell me what rendering code or line is crashing. Also which tab are you in?

**Comment by sekwah41** [comment]
Ok I found the issue. This was because the mapping changed due to the fact I forgot to add mappings beforehand so a lot were missing. I've also added override tags so that this cant compile if an issue like this happens again.

**Comment by sekwah41** [comment]
#blame @UpcraftLP ;)
