### ISSUE TITLE
fix: NarutoMod:PacketHandler/]: Client attempted to connect with a different version of the mod. Server Version: 1.8.0 Client Version: ABSENT

### ISSUE THREAD

**Issue by MachinegunMarty** [sekwah41/Naruto-Mod#228]
I'm setting up a 1.20.1 server.
I am using Forge 47.1.0.
I am using:
- NarutoMod-1.20-1.8.0-universal.jar
- SekCLib-1.20-1.0.2-universal.jar

The server console get's spammed with the following message:
NarutoMod:PacketHandler/]: Client attempted to connect with a different version of the mod. Server Version: 1.8.0 Client Version: ABSENT

This message get's spammed as soon as the server starts.
I can log into the server with a client, but the message keeps spamming.
Searched in my router if someone is trying to connect to my server, but can't find anything.

**Comment by sekwah41** [comment]
I'll have to check if this is an artifact of how the server status part is done or where it triggers from. Either I need to add an edge case for this or I need to raise a bug with forge.

**Comment by sekwah41** [comment]
Added a fix for this, will be in the next update.

**Comment by JELLYMAN206** [comment]
I seem to still be getting this log spam in the latest version

**Comment by sekwah41** [comment]
Made the fix but just got a bit busy and forgot to release it. Will be working on Naruto mod more starting in the next two weeks :)
