### ISSUE TITLE
Shadow clones should sprint towards enemies

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Naruto-Mod#27]
At the moment you can basically out-walk them.

**Comment by WolfNightAsh** [comment]
When your target starts sprinting then your clones chase and copy when your target jumps up blocks and stuff. And they will act like a real player and chase them the proper way, like a pursuit clone (used by Yamato) how it chased the target (but obviously it would hide from the enemy in that situation).

**Comment by Yagah** [comment]
When using shadow clone jutsu in the latest release of your mod, if you are wearing any sort of helmet, your shadowclones will appear with the boots of that armor. Ex: *Wearing only a leather helment*- Shadow clones spawn with a leather helmet AND leather boots.

**Comment by sekwah41** [comment]
@Yagah this will be raised as a seperate issue as it is a bug

**Comment by sekwah41** [comment]
Test
