### ISSUE TITLE
QoL Features

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Naruto-Mod#29]
The first feature I will list for this is quick combo buttons to swap out. I will look to add a nicer config altering menu to quick swap the key layout but this will be designed for anyone who has issues hitting combos due to any impairments. (good example is think of custom controllers like the customisable version Microsoft made)

First features should be quick combo buttons. Though generally an overall thing that should be added in the recode is possibly a slow effect while casting to slow people down a bit (tho may not do that part) while casting even without doing a combo though the quick combos should be done at a moderate rate though not too fast. Combos wont be too long anyway so people not using this would have the advantage of easier access to far more abilities rather than trying to slap specific keys for loads of abilities.

Input on how to do this right or further QoL features would be helpful, we want to make this mod playable by as many people as possible :D

**Comment by UpcraftLP** [comment]
- [x] `/jutsu list` command
