### ISSUE TITLE
Shows up but doesn't work (or something)

### ISSUE THREAD

**Issue by Propec0** [sekwah41/Naruto-Mod#55]
![Capture](https://user-images.githubusercontent.com/54221153/63217731-7b0b2700-c100-11e9-91ee-407da679a19f.PNG)
 It acknowledges that the Naruto Mod is attached but it doesn't show up in the mod list and nothing shows up in the game.

**Comment by Propec0** [comment]
Any reason why this might happen? Even if its not the mods fault, i have the latest of forge, all put in the mods folder, updated Java. Did I miss anything?

**Comment by UpcraftLP** [comment]
> Did I miss anything?

yes, the fact that the mod is for 1.7.10 ONLY for the time being

**Comment by sekwah41** [comment]
Wait what >.>

**Comment by sekwah41** [comment]
Ahh so the branding file is detected but nothing else. Sorry but 1.12 isnt supported atm.
