### ISSUE TITLE
 Add jutsu and clans

### ISSUE THREAD

**Issue by Gtafgu** [sekwah41/Naruto-Mod#69]
Rasengan
and
if you do this once on the server joint you have to select a clan and you can then set where it should teleport in config
sorry for my english my english is bad

**Comment by CatWithTh3Gat** [comment]
_Patience_

**Comment by sekwah41** [comment]
This is for issues. Adding something like this isn't an issue for me to fix. Feel free to post a suggestion on the discord but this is not the right place to post these.

**Comment by sekwah41** [comment]
While suggestions are welcome here, it's for existing features mostly, not to just list a load of things you want.
