### ISSUE TITLE
shadowclone different

### ISSUE THREAD

**Issue by melony202** [sekwah41/Naruto-Mod#73]
hey im having a problem here so when i shadowclone jutsu or the multi one the shadowclone is like different its not the same skin like me but instead its a steve skin i tried to find it everywhere even on yt but then there is no solution so pls help me fix this i dont want my shadowclone to be a steve skin.

**Comment by sekwah41** [comment]
are you using t-launcher?

**Comment by sekwah41** [comment]
Also are there any mods you have added to specifically alter or add skins?

**Comment by melony202** [comment]
> what launcher are you using?

im using tlauncher

**Comment by sekwah41** [comment]
Theres your problem

**Comment by melony202** [comment]
> Also are there any mods you have added to specifically alter or add skins?

i only have one mod the naruto mod

**Comment by melony202** [comment]
> Also are there any mods you have added to specifically alter or add skins?

now how do i fix this issue?

**Comment by sekwah41** [comment]
Dont use t-launcher if you want skins to work properly

**Comment by melony202** [comment]
> Dont use t-launcher if you want skins to work properly

oh ok thx ill just install another launcher later or next month
